openapi: 3.0.0
info:
  title: Auth.v1
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000/v1/auth'
    description: local
paths:
  /sign_in:
    post:
      summary: サインインする
      operationId: post-sign_in
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: object
                  required:
                    - email
                    - password
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      format: password
              required:
                - account
  /sign_up:
    post:
      summary: サインアップする
      operationId: post-sign_up
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUpResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: object
                  required:
                    - email
                    - password
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      format: password
              required:
                - account
  /verify_email:
    get:
      summary: メールアドレスを確認して、本登録を完了する
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Account.yaml
      operationId: get-verify_email
      parameters:
        - schema:
            type: string
          in: query
          name: token
          description: email_verification_token
          required: true
components:
  schemas:
    SignInResponse:
      title: SignInResponse
      type: object
      properties:
        account:
          $ref: ../models/Account.yaml
        token:
          type: string
    SignUpResponse:
      title: SignInResponse
      type: object
      properties:
        account:
          $ref: ../models/Account.yaml
        token:
          type: string
